"""empty message

Revision ID: 1b1333c2982f
Revises: 
Create Date: 2019-06-02 10:59:30.318259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b1333c2982f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pers_details', sa.Column('hiretime', sa.DateTime(), nullable=True))
    op.drop_column('pers_details', 'hiredate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pers_details', sa.Column('hiredate', mysql.DATETIME(), nullable=True))
    op.drop_column('pers_details', 'hiretime')
    # ### end Alembic commands ###
