"""empty message

Revision ID: 2d7f88a54131
Revises: 
Create Date: 2019-06-09 10:09:36.322434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d7f88a54131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enterprise_base', 'address',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('enterprise_base', 'ceo',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('enterprise_base', 'ceo_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('enterprise_base', 'enterprise_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('enterprise_base', 'enterprise_type',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('enterprise_base', 'password',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enterprise_base', 'password',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('enterprise_base', 'enterprise_type',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('enterprise_base', 'enterprise_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('enterprise_base', 'ceo_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('enterprise_base', 'ceo',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('enterprise_base', 'address',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
