"""empty message

Revision ID: 539469dfc6e5
Revises: b4e338b2907b
Create Date: 2019-06-02 11:20:57.954014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539469dfc6e5'
down_revision = 'b4e338b2907b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(length=1024), nullable=True),
    sa.Column('speciality', sa.String(length=1024), nullable=True),
    sa.Column('graduation', sa.String(length=1024), nullable=True),
    sa.Column('training', sa.String(length=1024), nullable=True),
    sa.Column('career', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_details')
    # ### end Alembic commands ###
