"""empty message

Revision ID: a1f518ce2a56
Revises: 19e376d3f9a7
Create Date: 2019-06-02 16:05:32.335025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f518ce2a56'
down_revision = '19e376d3f9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'enterprise_base', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enterprise_base', type_='unique')
    # ### end Alembic commands ###
