"""empty message

Revision ID: b4e338b2907b
Revises: 1b1333c2982f
Create Date: 2019-06-02 11:17:48.533030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4e338b2907b'
down_revision = '1b1333c2982f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_details', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('temp_details', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_details', sa.Column('num', mysql.INTEGER(display_width=16), autoincrement=True, nullable=False))
    op.drop_column('temp_details', 'id')
    # ### end Alembic commands ###
