"""empty message

Revision ID: d55340b09ee1
Revises: 
Create Date: 2019-06-02 14:42:02.155441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55340b09ee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pers_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('section', sa.String(length=16), nullable=True),
    sa.Column('postion', sa.String(length=16), nullable=True),
    sa.Column('tel', sa.String(length=16), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('native', sa.String(length=16), nullable=True),
    sa.Column('education', sa.String(length=16), nullable=True),
    sa.Column('graduation', sa.String(length=64), nullable=True),
    sa.Column('hiredate', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('wechat', sa.String(length=32), nullable=True),
    sa.Column('qq', sa.String(length=16), nullable=True),
    sa.Column('emergency_contact', sa.String(length=32), nullable=True),
    sa.Column('contact_tel', sa.String(length=16), nullable=True),
    sa.Column('hobby', sa.String(length=128), nullable=True),
    sa.Column('speciality', sa.String(length=128), nullable=True),
    sa.Column('training', sa.String(length=3072), nullable=True),
    sa.Column('career', sa.String(length=5120), nullable=True),
    sa.Column('signin_time', sa.DateTime(), nullable=True),
    sa.Column('signout_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('is_astive', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pers_details')
    # ### end Alembic commands ###
